services:
  - type: web
    name: artwork-sequencer
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATA_DIR
        value: /data
    disk:
      name: artwork-sequencer-data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
    plan: starter